services:
  - type: web
    name: cnpj-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium && python -m playwright install-deps chromium
    startCommand: gunicorn app:app
