services:
  - type: web
    name: cnpj-backend
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
