services:
  - type: web
    name: cnpj-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CHROME_BIN
        value: /opt/render/.chrome/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /opt/render/.chromedriver/bin/chromedriver
